In [360]:
import tensorflow as tf
import tensorflow_addons as tfa
from tensorflow import keras
import pandas as pd
import numpy as np

In [361]:
data=pd.read_csv('preprocesseddata.csv')

In [362]:
data
ctr=0
for i in range(len(data.Attrition)):
  if data["Attrition"][i]==1:
    ctr=ctr+1
print(ctr) 

237


In [363]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(units=512, activation=tf.nn.relu),
    tf.keras.layers.Dense(1, activation=tf.nn.sigmoid)
])


In [364]:
model.compile(optimizer = tf.optimizers.Adam(),
              loss = tf.keras.losses.BinaryCrossentropy(),
              metrics=[tf.keras.metrics.AUC()])

In [365]:
from sklearn.model_selection import train_test_split
y=np.array(data.Attrition)
data.drop(['Attrition'],axis=1,inplace=True)
X_train, X_test, y_train, y_test = train_test_split(data, y, test_size=0.2, random_state=0)
print(np.sum(y_test))
y_train=y_train.reshape(1176,1)
y_train

49


array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [366]:
model.fit(X_train,y_train,epochs=400)

Epoch 1/400
37/37 [==============================] - 1s 2ms/step - loss: 45.8146 - auc_6: 0.5250
Epoch 2/400
37/37 [==============================] - 0s 2ms/step - loss: 7.4114 - auc_6: 0.5190
Epoch 3/400
37/37 [==============================] - 0s 2ms/step - loss: 4.4962 - auc_6: 0.5262
Epoch 4/400
37/37 [==============================] - 0s 2ms/step - loss: 16.0889 - auc_6: 0.4996
Epoch 5/400
37/37 [==============================] - 0s 2ms/step - loss: 3.6993 - auc_6: 0.5938
Epoch 6/400
37/37 [==============================] - 0s 2ms/step - loss: 8.5285 - auc_6: 0.5486
Epoch 7/400
37/37 [==============================] - 0s 2ms/step - loss: 5.7080 - auc_6: 0.5701
Epoch 8/400
37/37 [==============================] - 0s 2ms/step - loss: 11.1338 - auc_6: 0.5374
Epoch 9/400
37/37 [==============================] - 0s 2ms/step - loss: 6.9306 - auc_6: 0.5649
Epoch 10/400
37/37 [==============================] - 0s 2ms/step - loss: 3.9747 - auc_6: 0.5844
Epoch 11/400
37/37 [================

In [367]:
pred=model.predict(X_test)

In [368]:
pred

array([[9.98527527e-01],
       [2.23054975e-01],
       [9.99922514e-01],
       [9.99921560e-01],
       [9.99924064e-01],
       [5.30694723e-02],
       [9.99968529e-01],
       [6.66507840e-01],
       [3.74705201e-06],
       [9.97828603e-01],
       [9.99560654e-01],
       [7.88639128e-01],
       [8.19183588e-01],
       [9.96247530e-01],
       [9.88197267e-01],
       [5.12233377e-03],
       [9.65599537e-01],
       [9.57486629e-02],
       [2.31576264e-01],
       [9.69942570e-01],
       [7.10715353e-01],
       [9.35702264e-01],
       [1.70058906e-02],
       [7.20867515e-01],
       [9.99989390e-01],
       [9.99656498e-01],
       [9.25521553e-02],
       [9.98006225e-01],
       [9.98634040e-01],
       [9.28295135e-01],
       [4.48155403e-03],
       [9.94934976e-01],
       [7.79018641e-01],
       [7.52420664e-01],
       [4.90289032e-01],
       [5.53146005e-03],
       [9.99990046e-01],
       [1.42620027e-01],
       [5.80495119e-01],
       [6.54858530e-01],


In [369]:
p=pred>=0.5

In [370]:
y_test

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0])

In [371]:
p.astype(int)

array([[1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
    

In [372]:
print(np.sum(p))

172


In [373]:
np.sum(y_test)

49

In [374]:
p.shape

(294, 1)

In [375]:
from sklearn.metrics import f1_score

In [376]:
f1_score(y_test,p)

0.42533936651583704

In [377]:
y_test

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0])

In [378]:
p

array([[ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [